dist: xenial

language: clojure

node_js:
  - "10"

install: make deps

script: make travis-test

before_install:

# Retrieve IPFS client
- wget https://dist.ipfs.io/ipfs-update/v1.5.2/ipfs-update_v1.5.2_linux-amd64.tar.gz
  -O ipfs-update.tar.gz
- tar -xzf ipfs-update.tar.gz

# Update to the latest IPFS client
- ipfs-update/ipfs-update install latest
- ipfs init

# Update Node Version through nvm (latest LTS version)
- nvm install 10.16.3
- nvm use 10.16.3

before_script:

# Start ganache-cli as background process
- make testnet > /dev/null &

# Start IPFS Daemon as background process
- make ipfs > /dev/null &

# Deploy Truffle Migration
- make deploy
